context: {}
package:

  name: molskill
  version: '1.0'

source:
  path: ../

build:
  number: 2


requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - matplotlib >=3.5.2
    - numpy >=1.23.1
    - pandas >=1.4.2
    - pip >=22.1.2
    - python >=3.9
    - scikit-learn >=1.0.1
    - scipy >=1.8.1
    - tqdm >=4.64.0
    - pytorch >=1.11
    - sel(linux64): cudatoolkit >=11.3
    - rdkit >=2022.03.3
    - statsmodels >=0.13.2
    - pytorch-lightning >=1.6.3
    - tensorboard >=2.9.0

about:
  home: https://github.com/microsoft/molskill
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josejimenezluna

